name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Check formatting with black
        uses: psf/black@stable
      - uses: isort/isort-action@master
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
      - name: Lint with flake8
        run: flake8 --count --statistics
      - name: Static analysis with mypy
        run: mypy
      - name: Unittests with pytest
        run: pytest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
      - name: Python Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: python-build-cache
          key: ${{ runner.os }}-python-build-cache-${{ hashFiles('**/python.sum') }}
      - name: Inject python-build-cache into Docker
        uses: overmindtech/buildkit-cache-dance/inject@main
        with:
          cache-source: python-build-cache
      - name: Build docker container
        uses: docker/build-push-action@v3
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Extract python-build-cache from Docker
        uses: overmindtech/buildkit-cache-dance/extract@main
        with:
          cache-source: python-build-cache
      - name: Scan docker image
        uses: anchore/scan-action@v3
        with:
          image: localbuild/testimage:latest
          fail-build: false
          output-format: table
