name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check formatting with black
        uses: psf/black@stable
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "dev-requirements.txt"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint with flake8
        run: flake8 --count --exit-zero --statistics
      - name: Static analysis with mypy
        run: mypy
      - name: Unittests with pytest
        run: pytest
